use scott;

select * from emp;
CREATE INDEX idx_emp_sal ON EMP(SAL);

SELECT * FROM EMP;
SELECT DEPTNO, ENAME, JOB FROM EMP;

SELECT DISTINCT deptno FROM EMP;

SELECT DISTINCT deptno, job FROM EMP;

SELECT SAL FROM emp;

SELECT ALL DEPTNO, JOB FROM emp;
SELECT DEPTNO, JOB FROM EMP;

SELECT ENAME, SAL, SAL*12*COMM AS ANNSAL, COMM FROM EMP;

SELECT * FROM EMP ORDER BY sal ASC;   -- 오름차순
SELECT * FROM EMP ORDER BY sal DESC;  -- 내림차순

SELECT * FROM EMP ORDER BY empno ASC;
SELECT * FROM EMP ORDER BY empno DESC;

SELECT * FROM EMP ORDER BY deptno ASC, sal DESC;

SELECT * FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP WHERE empno = 7782;

SELECT * FROM EMP WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
SELECT * FROM EMP WHERE DEPTNO = 30 OR  JOB = 'SALESMAN';
SELECT * FROM EMP WHERE DEPTNO = 20 OR EMPNO = 7782;
SELECT * FROM EMP WHERE DEPTNO = 20 AND SAL > 1000;

SELECT * FROM EMP WHERE sal * 12 = 36000;
SELECT * FROM EMP WHERE sal >= 3000;
SELECT * FROM EMP WHERE SAL >= 2500 AND JOB = 'ANALYST';
SELECT * FROM EMP WHERE ENAME >= 'F';

SELECT * FROM EMP WHERE SAL != 3000;
# SELECT * FROM EMP WHERE SAL <> 3000;
# SELECT * FROM EMP WHERE NOT SAL = 3000;

SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');
# SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'SALESMAN' OR JOB = 'CLERK';
# SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT empno, ename, sal, deptno FROM emp;

SELECT ename, sal, (sal * 0.13) AS bonus, deptno FROM emp WHERE DEPTNO = 10;


# SELECT * FROM EMP WHERE SAL >= 2000 AND SAL <= 3000;
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 3000;
# SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP WHERE ENAME LIKE '%S';

SELECT * FROM EMP WHERE ENAME LIKE 'S%';

SELECT * FROM EMP WHERE ENAME LIKE '%AM%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%AM%';


SELECT * FROM EMP WHERE COMM = NULL;

SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;
SELECT * FROM EMP WHERE MGR  IS NOT NULL;


SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;


SELECT ENAME, UPPER(ENAME), LOWER(ENAME), LENGTH(ENAME) FROM EMP;

SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5) FROM EMP;

SELECT '010-1234-5678' AS REPLACE_BEFORE,
       REPLACE('010-1234-5678', '-', ' ') AS REPLACE_1,
       REPLACE('010-1234-5678', '-', '')  AS REPLACE_2;

SELECT * FROM EMP WHERE JOB = 'CLERK';
SELECT * FROM EMP WHERE SAL >= 1000;
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;
SELECT * FROM EMP WHERE ENAME LIKE '%R';
SELECT * FROM EMP WHERE ENAME LIKE 'M%' OR DEPTNO = 10;
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
SELECT * FROM EMP WHERE SAL >= 1000 AND SAL <= 2000;
SELECT * FROM EMP WHERE SAL IN (1000, 2000);
SELECT DISTINCT DEPTNO FROM EMP;
SELECT * FROM EMP ORDER BY SAL DESC;
SELECT * FROM EMP ORDER BY SAL ASC;


SELECT NOW()    AS NOW,                          -- 날짜 + 시간
       CURDATE() AS TODAY,                        -- 날짜만
       CURDATE() - INTERVAL 1 DAY AS YESTERDAY,
       CURDATE() + INTERVAL 1 DAY AS TOMORROW;

SELECT EMPNO, ENAME, HIREDATE,
       DATE_ADD(HIREDATE, INTERVAL 120 MONTH) AS WORK10YEAR
FROM EMP;

SELECT ENAME FROM EMP WHERE DATE_ADD(HIREDATE, INTERVAL 384 MONTH) > NOW();


SELECT empno, ename, sal, comm, sal + comm,
       IFNULL(COMM, 0), sal + IFNULL(comm, 0)
FROM EMP;

SELECT EMPNO, ENAME, COMM,
       IF(COMM IS NOT NULL, 'O', 'X'),
       IF(COMM IS NOT NULL, SAL*12+COMM, SAL*12) AS ANNUAL
FROM EMP;

SELECT * FROM EMP WHERE HIREDATE >= '1980-12-17';