# SELECT [조회할 열1, 열2, ..., 열N]
# FROM   [조회할 테이블]
# WHERE  [조건식]
# GROUP BY [그룹화할 열 지정(여러 개 가능)]
# ORDER BY [정렬할 열 지정];
USE scott;

SELECT AVG(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT AVG(SAL), DEPTNO, JOB
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;


/*
SELECT [조회할 열1, 열2, ..., 열N]
FROM   [테이블명]
WHERE  [조건식]
GROUP BY [그룹화할 열 지정(여러 개 가능)]
HAVING [그룹화된 결과를 제한하는 조건]
ORDER BY [정렬할 열 지정];
*/

SELECT AVG(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT AVG(SAL), DEPTNO, JOB
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;


/*
SELECT [조회할 열1, 열2, ..., 열N]
FROM   [테이블명]
WHERE  [조건식]
GROUP BY [그룹화할 열 지정(여러 개 가능)]
HAVING [그룹화된 결과를 제한하는 조건]
ORDER BY [정렬할 열 지정];
*/

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
WHERE SAL >= 3000
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;



SELECT AVG(SAL), MAX(SAL), MIN(SAL), COUNT(EMPNO)
FROM EMP
WHERE DEPTNO = 10;

SELECT DEPTNO, JOB, COUNT(EMPNO)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO;

SELECT AVG(SAL), MAX(SAL), MIN(SAL)
FROM EMP
GROUP BY JOB
ORDER BY AVG(SAL);

SELECT JOB, COUNT(EMPNO), MAX(SAL), MIN(SAL),
       ROUND(AVG(SAL), 1)
FROM EMP
GROUP BY JOB
ORDER BY COUNT(EMPNO) DESC;

SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING SUM(SAL) > 5000;

SELECT DEPTNO, AVG(SAL)
FROM EMP
WHERE SAL >= 1000
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000;

SELECT DEPTNO, JOB, COUNT(EMPNO)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO ASC;

SELECT DEPTNO, COUNT(*), SUM(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) > 4;


/*
SELECT [조회할 열1, 열2, ..., 열N]
FROM   [테이블명]
WHERE  [조건식]
GROUP BY [그룹화할 열 지정(여러 개 가능)] WITH ROLLUP;
*/

SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), MIN(SAL), AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB WITH ROLLUP;


-- UNION ALL
SELECT DEPTNO, NULL AS JOB, COUNT(*), MAX(SAL), MIN(SAL), AVG(SAL)
FROM EMP
GROUP BY DEPTNO
UNION ALL

SELECT NULL AS DEPTNO, JOB, COUNT(*), MAX(SAL), MIN(SAL), AVG(SAL)
FROM EMP
GROUP BY JOB;