USE scott;


-- 모든 경우의 수로 조합(곱집합) 되어 출력
SELECT *
FROM EMP, DEPT -- 여러 테이블 선언
ORDER BY EMPNO;

-- 등가 조인 (INNER JOIN)
-- 값이 일치하는 데이터를 기준으로 행을 선정
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DEPTNO, DEPT.DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMPNO;

SELECT e.EMPNO, e.ENAME, d.DEPTNO, d.DNAME
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.DEPTNO
  AND e.DEPTNO = 10
ORDER BY e.EMPNO, d.DEPTNO;

SELECT E.ENAME, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL >= 2000
ORDER BY E.DEPTNO DESC;


-- 비등가 조인
-- =이 아닌 범위 조건(BETWEEN 등) 으로 연결하는 조인.
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;


-- 자체 조인 (Self Join)
-- 같은 테이블을 두 번(별칭을 달리해서) 사용해 조인하는 방식
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;


-- NATURAL JOIN : 이름과 자료형이 같은 열을 자동으로 찾아 그 열을 기준으로 등가 조인
-- 일반 등가 조인
SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;
-- NATURAL JOIN
SELECT E.EMPNO, E.ENAME, DEPTNO, D.DNAME
FROM EMP E NATURAL JOIN DEPT D;


-- JOIN ~ USING : 공통 열을 직접 명시
SELECT E.EMPNO, E.ENAME, DEPTNO, D.DNAME
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE E.SAL >= 3000
ORDER BY DEPTNO, E.EMPNO;

-- JOIN ~ ON : 조건식을 직접 지정
SELECT E.EMPNO, E.ENAME,
       D.DEPTNO, D.DNAME
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE E.SAL >= 3000
ORDER BY D.DEPTNO, E.EMPNO;


-- OUTER JOIN (외부 조인)
-- 반대쪽에 짝이 없어도 모두 출력하는 조인

-- LEFT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2
                            ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- RIGHT OUTER JOIN
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 RIGHT OUTER JOIN EMP E2
                             ON (E1.MGR = E2.EMPNO)
ORDER BY E1.EMPNO;

-- FULL OUTER JOIN
-- 양쪽 모두 짝이 없어도 출력
-- MySQL은 FULL OUTER JOIN을 직접 지원하지 않는다. LEFT JOIN과 RIGHT JOIN 결과를 UNION으로 합쳐 같은 효과를 낸다.
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
UNION
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
ORDER BY EMPNO;


SELECT E.EMPNO, E.ENAME, DEPTNO, D.DNAME
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE E.SAL >= 3000
  AND E.MGR IS NOT NULL
ORDER BY DEPTNO;
