USE scott;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20;


SELECT EMPNO, ENAME, SAL          -- 열 3개
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO  -- 열 4개 → 오류
FROM EMP
WHERE DEPTNO = 20;

SELECT DEPTNO, EMPNO, ENAME, SAL
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO  -- 순서별 자료형 불일치 → 오류
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT SAL, JOB, DEPTNO, SAL      -- 자료형은 맞지만 의미가 엉킴
FROM EMP
WHERE DEPTNO = 20;


-- UNION : 중복 제거 → 한 번만 출력
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

-- UNION ALL : 중복 포함 → 두 번 모두 출력
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;


-- INTERSECT : 교집합 - 공통으로 존재하는 데이터만 출력
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;


-- INTERSECT 미지원 버전에서의 대체 (IN 사용 예)
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
  AND EMPNO IN (SELECT EMPNO FROM EMP);


-- EXCEPT : 차집합 - 앞 SELECT문의 결과에서, 뒤 SELECT문의 결과에 있는 데이터를 빼고 출력
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
EXCEPT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;