# 서브쿼리: SQL문을 실행하는 데 필요한 데이터를 추가로 조회하기 위해, SQL문 내부에서 사용하는 SELECT문을 의미한다.\
USE scott;

-- 1. 사원 이름이 JONES인 사원의 급여 출력
SELECT SAL
FROM EMP
WHERE ENAME = 'JONES';
-- 2. 급여가 2975보다 높은 사원 정보 출력
SELECT ENAME
FROM EMP
WHERE SAL > 2975;
-- 1 + 2. JONES의 급여보다 높은 급여를 받는 사원 출력
--   → 2975라는 값을 직접 쓰는 대신, 1번 쿼리를 서브쿼리로 넣는다
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'JONES');


SELECT E.ENAME, D.DNAME, E.SAL, E.JOB
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');

SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.SAL > (SELECT AVG(SAL) FROM EMP);

SELECT *
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
  AND E.DEPTNO = 20
  AND E.SAL > (SELECT AVG(SAL) FROM EMP);

SELECT *
FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);


-- 단일행 서브쿼리	1개	=, >, <, >=, <=, <>
-- 다중행 서브쿼리	여러 개	IN, NOT IN, ANY, ALL, EXISTS
-- 다중행일 때 단일행 연산자를 사용하면 오류
SELECT E10.ENAME, D.DNAME
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
     (SELECT * FROM DEPT) D
WHERE E10.DEPTNO = D.DEPTNO;

SELECT EMPNO, ENAME, JOB, SAL,
       (SELECT GRADE FROM SALGRADE
        WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
       DEPTNO,
       (SELECT DNAME FROM DEPT
        WHERE E.DEPTNO = DEPT.DEPTNO) AS DEPT
FROM EMP E;